# It contains all the configs required in the project

data:
  source_data_url: "Enter URL here"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages

