# It contains all the configs required in the project

data:
  source_data_url: "Enter URL here"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: data
  bad_data_dir: bad_data
  parent_data_dir: PetImages
  model_dir: model
  init_model_file: init_model.h5
  early_stop_file: best_weight.h5
  trained_model_file: trained_model.h5
  CSV_file: log.csv

params:
  img_shape: [180,180,3]
  lr: 0.001
  loss: sparse_categorical_crossentropy
  metrics: ["accuracy"]
  validation_split: 0.2
  batch_size: 32
  seed: 42
  buffer_size: 32
  epochs: 3

